2025-04-20 14:19:13,410 INFO    MainThread:1342631 [wandb_setup.py:_flush():76] Configure stats pid to 1342631
2025-04-20 14:19:13,410 INFO    MainThread:1342631 [wandb_setup.py:_flush():76] Loading settings from /home/md5121/.config/wandb/settings
2025-04-20 14:19:13,410 INFO    MainThread:1342631 [wandb_setup.py:_flush():76] Loading settings from /scratch/md5121/okhatisathi/tacotron2/wandb/settings
2025-04-20 14:19:13,410 INFO    MainThread:1342631 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-04-20 14:19:13,410 INFO    MainThread:1342631 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-04-20 14:19:13,410 INFO    MainThread:1342631 [wandb_init.py:_log_setup():461] Logging user logs to /scratch/md5121/okhatisathi/tacotron2/wandb/run-20250420_141913-zf7hs2bg/logs/debug.log
2025-04-20 14:19:13,410 INFO    MainThread:1342631 [wandb_init.py:_log_setup():462] Logging internal logs to /scratch/md5121/okhatisathi/tacotron2/wandb/run-20250420_141913-zf7hs2bg/logs/debug-internal.log
2025-04-20 14:19:13,411 INFO    MainThread:1342631 [wandb_init.py:_jupyter_setup():411] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x1554820c8b38>
2025-04-20 14:19:13,412 INFO    MainThread:1342631 [wandb_init.py:init():495] calling init triggers
2025-04-20 14:19:13,412 INFO    MainThread:1342631 [wandb_init.py:init():499] wandb.init called with sweep_config: {}
config: {}
2025-04-20 14:19:13,412 INFO    MainThread:1342631 [wandb_init.py:init():548] starting backend
2025-04-20 14:19:13,412 INFO    MainThread:1342631 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-20 14:19:13,414 INFO    MainThread:1342631 [backend.py:ensure_launched():217] starting backend process...
2025-04-20 14:19:13,425 INFO    MainThread:1342631 [backend.py:ensure_launched():222] started backend process with pid: 1346693
2025-04-20 14:19:13,426 INFO    MainThread:1342631 [wandb_init.py:init():558] backend started and connected
2025-04-20 14:19:13,438 INFO    MainThread:1342631 [wandb_run.py:_label_probe_notebook():1084] probe notebook
2025-04-20 14:19:13,439 INFO    MainThread:1342631 [wandb_run.py:_label_probe_notebook():1094] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-20 14:19:13,440 INFO    MainThread:1342631 [wandb_init.py:init():634] updated telemetry
2025-04-20 14:19:13,504 INFO    MainThread:1342631 [wandb_init.py:init():666] communicating run to backend with 30 second timeout
2025-04-20 14:19:14,981 INFO    MainThread:1342631 [wandb_run.py:_on_init():1919] communicating current version
2025-04-20 14:19:15,063 INFO    MainThread:1342631 [wandb_run.py:_on_init():1923] got version response upgrade_message: "wandb version 0.19.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-04-20 14:19:15,063 INFO    MainThread:1342631 [wandb_init.py:init():700] starting run threads in backend
2025-04-20 14:19:18,250 INFO    MainThread:1342631 [wandb_run.py:_console_start():1893] atexit reg
2025-04-20 14:19:18,251 INFO    MainThread:1342631 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.WRAP
2025-04-20 14:19:18,253 INFO    MainThread:1342631 [wandb_run.py:_redirect():1803] Wrapping output streams.
2025-04-20 14:19:18,259 INFO    MainThread:1342631 [wandb_run.py:_redirect():1827] Redirects installed.
2025-04-20 14:19:18,259 INFO    MainThread:1342631 [wandb_init.py:init():732] run started, returning control to user process
2025-04-20 14:21:09,661 INFO    MainThread:1342631 [wandb_run.py:_finish():1680] finishing run md5121-new-york-university/tacotron2/zf7hs2bg
2025-04-20 14:21:09,663 INFO    MainThread:1342631 [jupyter.py:save_history():435] not saving jupyter history
2025-04-20 14:21:09,663 INFO    MainThread:1342631 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2025-04-20 14:21:09,663 INFO    MainThread:1342631 [wandb_init.py:_jupyter_teardown():393] cleaning up jupyter logic
2025-04-20 14:21:09,664 INFO    MainThread:1342631 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2025-04-20 14:21:09,666 INFO    MainThread:1342631 [wandb_run.py:_restore():1834] restore
2025-04-20 14:21:10,353 INFO    MainThread:1342631 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 733
  total_bytes: 733
}

2025-04-20 14:21:10,678 INFO    MainThread:1342631 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 733
  total_bytes: 733
}

2025-04-20 14:21:11,423 INFO    MainThread:1342631 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 733
  total_bytes: 16422
}

2025-04-20 14:21:11,524 INFO    MainThread:1342631 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 733
  total_bytes: 16422
}

2025-04-20 14:21:11,625 INFO    MainThread:1342631 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 733
  total_bytes: 16422
}

2025-04-20 14:21:11,726 INFO    MainThread:1342631 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 733
  total_bytes: 16422
}

2025-04-20 14:21:11,827 INFO    MainThread:1342631 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 733
  total_bytes: 16422
}

2025-04-20 14:21:11,928 INFO    MainThread:1342631 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13847
  total_bytes: 16422
}

